<?php 
    /*
        implements hook_block_info()
    */
    function issue_tracking_block_info() {
        $blocks = array();
        $blocks['latest_issues'] = array(
          'info' => t('Latest Issues'),
          'cache' => DRUPAL_CACHE_PER_ROLE,
        );
        return $blocks;
      }

    /*  
        implements hook_blook_view()
    */
    function issue_tracking_block_view($delta = '') {
        $block = array();
        switch ($delta) {
          case 'latest_issues':
            $uid = $GLOBALS['user']->uid;
            $query = db_query("SELECT n.title, n.body, n.issue_type, n.priority, n.status, n.duedate
                            FROM {node} n INNER JOIN {assignee} a ON n.nid = a.entity_id WHERE a.assignee_target_id = :uid AND n.type = 'issue_tracking' DESC LIMIT 3", array(':uid' => $uid));
            $output = '<ul>';
            foreach ($query as $row) {
              $output .= '<li><a href="/node/' . $row->nid . '">' . $row->title . '</a></li>'. '<br/>' .
                            $row->body. '<br/>' . $row->issue_type. '<br/>' . $row->priority . '<br/>' . 
                            $row->status . '<br/>' . $row->duedate ;
            }
            $output .= '<li><a href="/my-issues">View last 3 issues</a></li>';
            $output .= '</ul>';
            $block['content'] = array(
              '#markup' => $output,
            );
            break;
        }
        return $block;  //The block can be placed wherever the admin user like
    }
?>